import Head from "next/head";
import styles from "@/styles/Home.module.css";
import useFetch from "@/utils/useFetch";
import { useEffect, useState } from "react";
import TopSection from "@/components/topSection";
import MovieList from "@/components/movieList";

export default function Home() {
  const [products, setProducts] = useState([]);
  const [selected, setSelected] = useState([]);
  const { data, loading, error } = useFetch(
    "http://localhost:3000/api/content"
  ); //fetch Api

  useEffect(() => {
    if (data) {
      //set list of movie in the state
      setProducts(data.blocks[0].products);
    }
  }, [data]);

  const callBackMovieDetail = (data) => {
    //set selected movies less than 3 numbers and non-repetitive
    if (selected.length < 2 && selected.indexOf(data) < 0) {
      setSelected((selected) => [...selected, data]);
    }
  };

  const resetSelectedMovies = () => {
    //reset the selected movies
    setSelected([]);
  };

  if (error) {
    return (
      <main className={styles.main}>
        <p className={styles.subTitle}>{error.message}</p>
      </main>
    );
  }

  if (loading) {
    return (
      <main className={styles.main}>
        <p className={styles.loading}>isLoading...</p>
      </main>
    );
  }

  return (
    <>
      <Head>
        <title>ViaPlay group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className={styles.title}>Are these similar?</p>
        <TopSection
          selected={selected}
          resetSelectedMovies={() => resetSelectedMovies()}
        />
        <MovieList
          callBackMovieDetail={(data) => callBackMovieDetail(data)}
          products={products}
          selected={selected}
        />
      </main>
    </>
  );
}
